front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_qsnpage:
    path:     /qui-sommes-nous
    defaults: { _controller: FrontBundle:Default:qsn }

front_contact:
    path:     /nous-contacter
    defaults: { _controller: FrontBundle:Default:contacter }

front_investor_homepage:
    path:     /investor
    defaults: { _controller: FrontBundle:Default:investoreHome }

front_tenant_homepage:
    path:     /tenant
    defaults: { _controller: FrontBundle:Default:tenantHome }

front_tenant_map:
    path:     /tenant/map
    defaults: { _controller: FrontBundle:Default:tenantMap }

front_investor_register:
    path:     /investor-register
    defaults: { _controller: FrontBundle:Default:investorRegister }

front_tenant_register:
    path:     /tenant-register
    defaults: { _controller: FrontBundle:Default:tenantRegister}