agence_homepage:
    path:     /
    defaults: { _controller: AgenceBundle:Default:index }

agence_map:
    path:     /map
    defaults: { _controller: AgenceBundle:Default:map }

agence_frame:
    path:     /frame
    defaults: { _controller: AgenceBundle:Default:frame }

agence_list:
    path:    /list
    defaults: { _controller: AgenceBundle:Default:list }
