projet:
    resource: "@ProjetBundle/Resources/config/routing.yml"
    prefix:   /project

faq:
    resource: "@FaqBundle/Resources/config/routing.yml"
    prefix:   /faq

agence:
    resource: "@AgenceBundle/Resources/config/routing.yml"
    prefix:   /agency

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin