<?php

namespace UserBundle\Repository;

/**
 * InvestorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestorRepository extends \Doctrine\ORM\EntityRepository
{
}
