<?php

namespace UserBundle\Repository;

/**
 * TenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantRepository extends \Doctrine\ORM\EntityRepository
{
}
