UserBundle\Entity\Tenant:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\TenantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        statusTenant:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        birthday:
            type: datetime
            length: 255
            nullable: true
        relation:
            type: string
            length: 255
        status:
            type: string
            length: 255
        worktype:
            type: string
            length: 255
        child:
            type: string
            length: 255
        bail:
            type: string
            length: 255
        rent:
            type: string
            length: 255
        qsp:
            type: string
            length: 255
        docPI:
            type: string
            length: 255
            nullable: true
        docReleveUn:
            type: string
            length: 255
            nullable: true
        docReleveDeux:
            type: string
            length: 255
            nullable: true
        docReleveTrois:
            type: string
            length: 255
            nullable: true
        docJustifie:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    oneToOne:
        user:
            targetEntity: UserBundle\Entity\User
            mappedBy: tenant
            fetch: EAGER
            cascade: ["persist"]
            joinColumn:
                onDelete: CASCADE

    manyToOne:
        projet:
            targetEntity: ProjetBundle\Entity\Projet
            inversedBy: tenant
            joinColumn:
                name: projet_id
                referencedColumnName: id
