<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDjxhv9m\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDjxhv9m/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDjxhv9m.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDjxhv9m\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDjxhv9m\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Djxhv9m',
    'container.build_id' => '32edd1fd',
    'container.build_time' => 1543929795,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDjxhv9m');
